### ISSUE TITLE
Cinchize compatibility?

### ISSUE THREAD

**Issue by rikai** [bhaberer/cinch-cooldown#1]
So i'm trying to get this cinch plugin to work with [cinchize](https://github.com/netfeed/cinchize), specifically as part of [showbot](https://github.com/mutewinter/Showbot), but i cant seem to get it to work.

My cinchize.yml includes the following:
```yml
shared:
  cooldown:
    config:
      "#jb-test":
        global: "10"
        user: "20"
```

Which should be equivalent to:
```
c.shared[:cooldown] = { :config => { '#bottest' => { :global => 10 :user => 20 } }
```

I do indeed have `require 'cinch-cooldown'` and `enforce_cooldown` in the proper places, and the commands actually error if i get the syntax wrong with `'configuration_broken?': undefined method 'key?'`, so i can only assume i've gotten the syntax right... Is there something i'm missing or...?  I'd rather like to use cinch-cooldown with cinchize. :)
